project_id = "tsfwlereofjlxhjsarap"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "1000MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_runtime]
enabled = true
inspector_port = 8083

[functions.upload-video]
verify_jwt = true

[functions.get-video-url]
verify_jwt = true

[functions.delete-video]
verify_jwt = true

[functions.b2-upload]
verify_jwt = true

[functions.b2-signed-url]
verify_jwt = true

[functions.b2-delete]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.paystack-webhook]
verify_jwt = false

[functions.wallet-topup]
verify_jwt = true

[functions.refund-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.tv-show-upload]
verify_jwt = true

[functions.createSignedUploadUrl]
verify_jwt = true

[functions.slider-items]
verify_jwt = false

[functions.sections]
verify_jwt = true

[functions.content-sections]
verify_jwt = true

[functions.banners]
verify_jwt = true