project_id = "tsfwlereofjlxhjsarap"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = true

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = true
enable_email_change_confirmations = true
enable_phone_confirmations = true

[functions.unified-media-upload]
verify_jwt = true

[functions.unified-content-manager]
verify_jwt = true

[functions.unified-rental-manager]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.paystack-webhook]
verify_jwt = false

[functions.banners]
verify_jwt = false

[functions.sections]
verify_jwt = false

[functions.slider-items]
verify_jwt = false

[edge-runtime]
enabled = true
ip_version = "ipv4"
port = 54327
inspector_port = 54330