// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsfwlereofjlxhjsarap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzZndsZXJlb2ZqbHhoanNhcmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NDExOTIsImV4cCI6MjA3MTUxNzE5Mn0.S5QGd9HoLcG625AbAThoxSqWaqLc3_l9cr9fkvMOJSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});