// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcwrmemqctbuvnrsyuus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjd3JtZW1xY3RidXZucnN5dXVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MzUwMjMsImV4cCI6MjA3MDAxMTAyM30.-KHw43JWdFpcRhDz7BDY9prg946Mh1dZ1hkkXzJkIS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});